### ISSUE TITLE
Sort by date added?

### ISSUE THREAD

**Issue by jedahan** [zedtux/brewformulas.org#6]
Could we sort by date created, date updated, etc?

**Comment by zedtux** [comment]
@jedahan I'm working on the new version and in the new version, the homepage no more have the full list of formulae.

What was the purpose of this sorting? What did you want to achieve with that?
(I'm asking in order to see if I could implement something more or less close to this request in the new version).

**Comment by jedahan** [comment]
I think it is that sometimes I want to learn what new software is around, so seeing 'latest brews' is a way to find something I haven't tried before.

**Comment by zedtux** [comment]
Okay so actually, you have the "New since a week" tab which does that.
In the new version, I have added a "Trendings" line where you see the most viewed formulas.

I think this is addressing your requirements, and we can close this ticket, do you agree?

**Comment by jedahan** [comment]
Yes thank you!
