### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by eexit** [zedtux/brewformulas.org#66]
Hi,

Thanks for doing this, this is a cool asset for brew users.
I'd like to report the fact that the search engine looks broken. If I look for "Go", I got all the formulas...

**Comment by zedtux** [comment]
Hello and thank you @eexit.

If I understood well, you meant without filling in the search field, but clicking the "Search" button, you see all the formulae?
What's wrong with that?

Can you please tell what you did expect?

**Comment by eexit** [comment]
Lol, nope.

If I look up for "Go", the search results return me all formulas instead of the ones containing "Go".

Does this make sense or should I write it in French? 😉

**Comment by eexit** [comment]
Actually, after a quick test, I might have underestimate my issue: you should only look up for formula titles maybe instead of all the data related to a formula?

**Comment by eexit** [comment]
Maybe just narrow down the search to formula titles?

<img width="1301" alt="screen shot 2017-03-17 at 6 36 19 pm" src="https://cloud.githubusercontent.com/assets/57098/24055536/ab424886-0b40-11e7-8564-651513eea571.png">

**Comment by zedtux** [comment]
Ok now it's more clear.

Actually I think with this case "searching for "Go"", the results aren't nice because of the size of the criteria, but in another case with a longer criteria you'll get a better result set.

Searching only in the formulae title will limit the search and is not very good.

Maybe what could be done is first showing results on the title, and then the results on the description which would then show the "Go" formulae first, and then the rest.

What do you think about that?

**Comment by eexit** [comment]
Sounds like a decent idea! Love it. 👍

**Comment by zedtux** [comment]
Hello @Yann-R thank you for join this discussion :)

It's a good idea, it could a good way to solve this issue 👍
