### ISSUE TITLE
More description request actions

### ISSUE THREAD

**Issue by Yann-R** [zedtux/brewformulas.org#68]
Hello,

On  http://brewformulas.org, when a description is missing for a software, the user can use this link to request an update:

> No description available. You can request to update it by clicking this link. 

1) I don't know how this request will result in a new description (manually?) but sometimes a description can exist, but the user can notice that this description extracted is not perfect. Then, even for an existing description, such a link to request a description update could be useful.

2) Moreover, if those requests are moderated, then a link to propose a new text as description update could help collaborative work.

Possible?

**Comment by zedtux** [comment]
This link is just enqueuing the formula description fetcher job in order to retry to fetch the description (sometimes the job fails, relaunching it works).

The link is not shown when a description exists as it is supposed to be valid but you're right, an update could exists and brewformulas.org would need it.
I guess we could think of a validity date field and re-enqueue the description fetcher job after that date.

Regarding the formula description manual update, I always avoided it in order to not go with user authentication implementation, rights and permissions and so on in order to keep brewformulas.org simple.
+ as of now, nobody asked for being a moderator, and I don't want to do that, I'm a developer :)

**Comment by zedtux** [comment]
In the new version of BrewFormulas, I did this in order to help on understanding the purpose of the link:

![screen shot 2017-06-01 at 07 54 49](https://cloud.githubusercontent.com/assets/478564/26666323/9a6a6d50-469f-11e7-8a93-69c0a89e9b82.png)

What do you think?

To come back on your initial request, I saw that the formulas are now including a short description. I could implement something to show it on the page.

**Comment by zedtux** [comment]
@Yann-R I'm closing this ticket as you're not answering, but feel free to comment it when you want.
